// SPDX-License-Identifier: BSD-2-Clause
/*
 * Copyright (c) 2024, Synaptics Incorporated.
 */


#ifndef TEE_SYSCALL_NUMBERS_SYNA_H
#define TEE_SYSCALL_NUMBERS_SYNA_H

#define TEE_SCN_SYNA_MR_FILTER			0
#define TEE_SCN_SYNA_MR_FIND			1
#define TEE_SCN_SYNA_EXEC_CMD			2
#define TEE_SCN_SYNA_EXEC_CMD_EXT		3
#define TEE_SCN_SYNA_VERIFY_IMAGE		4
#define TEE_SCN_SYNA_MAP_REGISTER		5
#define TEE_SCN_SYNA_UNMAP_REGISTER		6
#define TEE_SCN_SYNA_VA2PA_CMD			7
#define TEE_SCN_SYNA_GET_OTP_RAW_CMD		8
#define TEE_SCN_SYNA_REGISTER_MEMORY		9
#define TEE_SCN_SYNA_UNREGISTER_MEMORY		10
#define TEE_SCN_SYNA_ADD_MEMORY_ACCESS		11
#define TEE_SCN_SYNA_MAP_MEMORY			12
#define TEE_SCN_SYNA_UNMAP_MEMORY		13
#define TEE_SCN_SYNA_GET_PHY_BY_MEMID		14
#define TEE_SCN_SYNA_GET_MEMID_BY_PHYS		15
#define TEE_SCN_SYNA_CHECK_MEMATRR		16
#define TEE_SCN_SYNA_REFCNT_OP			17
#define TEE_SCN_SYNA_RESERVE_RESERVATION	18
#define TEE_SCN_SYNA_RELEASE_RESERVATION	19
#define TEE_SCN_SYNA_RESERVATION_GET_INFO	20
#define TEE_SCN_SYNA_SET_GLOBALDATA		21
#define TEE_SCN_SYNA_GET_GLOBALDATA		22

#define TEE_SCN_SYNA_MUTEX_ALLOC		23
#define TEE_SCN_SYNA_MUTEX_DESTORY		24
#define TEE_SCN_SYNA_MUTEX_LOCK			25
#define TEE_SCN_SYNA_MUTEX_UNLOCK		26
#define TEE_SCN_SYNA_MUTEX_TRYLOCK		28

#define TEE_SCN_SYNA_SEMAPHORE_ALLOC		28
#define TEE_SCN_SYNA_SEMAPHORE_DESTORY		29
#define TEE_SCN_SYNA_SEMAPHORE_WAIT		30
#define TEE_SCN_SYNA_SEMAPHORE_POST		31
#define TEE_SCN_SYNA_SEMAPHORE_TIMEWAIT		32
#define TEE_SCN_SYNA_SEMAPHORE_TRYWAIT		33

#define TEE_SCN_SYNA_GET_SECUREKEY		34
#define TEE_SCN_SYNA_GET_SECUREKEY2		35

#define TEE_SCN_SYNA_GET_SA_ENTRY		36
#define TEE_SCN_SYNA_SET_SA_ENTRY		37
#define TEE_SCN_SYNA_GET_ACTIVE_ENTRIES		38
#define TEE_SCN_SYNA_GET_ACTIVE_SA_ENTRY	39

#define TEE_SCN_SYNA_MAX			39

/* Maximum number of allowed arguments for a synaptics syscall */
#define TEE_SVC_MAX_ARGS			7

#endif /* TEE_SYSCALL_NUMBERS_SYNA_H */
